<script lang="ts">
    import { onDestroy, onMount } from "svelte";
    import {
        VisualAssetAnimation,
        type VisualAssetAnimation as VisualAssetAnimationValue,
    } from "@workadventure/map-editor";
    import type {
        AssetGenerationLifecycleState,
        AssetGenerationProviderId,
        AssetGenerationRequest,
        AssetGenerationReference,
        AssetGenerationTarget,
    } from "../../Services/AssetGeneration/AssetGenerationTypes";
    import { EphemeralReferenceCollection } from "../../Services/AssetGeneration/ReferenceImageNormalizer";
    import { assetGenerationSession } from "../../Services/AssetGeneration/AssetGenerationSession";
    import { assetGenerationSettings } from "../../Services/AssetGeneration/AssetGenerationSettings";
    import {
        createWokaIdleFrameStage,
        createWokaSpriteSheetStage,
        type WokaGenerationTarget,
    } from "../../Services/AssetGeneration/StagedWokaGeneration";
    import {
        normalizeGeneratedRaster,
        type RasterOutputSize,
    } from "../../Services/AssetGeneration/RasterOutputNormalizer";
    import { aiGenerationSettingsVisibilityStore } from "../../Stores/AiGenerationSettingsVisibilityStore";
    import { BRANDING } from "../../Branding";
    import Button from "../UI/Button.svelte";
    import AnimatedAssetPreview from "./AnimatedAssetPreview.svelte";

    interface AcceptedGeneratedAsset {
        blob: Blob;
        title?: string;
        providerId: AssetGenerationProviderId;
        modelId: string;
        prompt: string;
        animation?: VisualAssetAnimationValue;
    }

    interface Props {
        target: AssetGenerationTarget;
        title?: string;
        promptPlaceholder?: string;
        promptGuidance?: string;
        generationRules?: string;
        presetReferences?: readonly AssetGenerationReference[];
        outputSize?: RasterOutputSize;
        frontIdleFirst?: boolean;
        initialPrompt?: string;
        promptReadOnly?: boolean;
        compact?: boolean;
        allowAnimation?: boolean;
        acceptLabel?: string;
        requiredReferenceCount?: number;
        maximumCostUsd?: number;
        authorizeGeneration?: () => Promise<string>;
        onGenerationFailure?: (reason: "provider-error" | "cancelled") => void | Promise<void>;
        onDiscardCandidate?: () => void | Promise<void>;
        onGenerated?: (asset: AcceptedGeneratedAsset) => void | Promise<void>;
        onUseImage?: () => void;
        onAccept: (asset: AcceptedGeneratedAsset) => void | Promise<void>;
    }

    let {
        target,
        title = "Create with AI",
        promptPlaceholder = "Describe what you want to create…",
        promptGuidance = "The image is generated by the provider you connect. Teapot applies the world style and asset constraints.",
        generationRules = "",
        presetReferences = [],
        outputSize,
        frontIdleFirst = false,
        initialPrompt = "",
        promptReadOnly = false,
        compact = false,
        allowAnimation = true,
        acceptLabel = "Use this asset",
        requiredReferenceCount,
        maximumCostUsd,
        authorizeGeneration,
        onGenerationFailure,
        onDiscardCandidate,
        onGenerated,
        onUseImage,
        onAccept,
    }: Props = $props();

    const references = new EphemeralReferenceCollection();
    // svelte-ignore state_referenced_locally -- prompts are intentionally seeded once when an editor mounts
    let prompt = $state(initialPrompt);
    let lifecycle = $state<AssetGenerationLifecycleState>("idle");
    let error = $state("");
    let referencePreviews: readonly { id: string; objectUrl: string }[] = $state([]);
    let candidate: Blob | null = $state(null);
    let candidateUrl = $state("");
    let candidateProvenance: Omit<AcceptedGeneratedAsset, "blob"> | null = $state(null);
    let wokaStage: "idle-frame" | "sprite-sheet" = $state("idle-frame");
    let acceptedIdleFrame: Blob | null = $state(null);
    let acceptedIdleFrameUrl = $state("");
    let animateAsset = $state(false);
    let animationFrameCount = $state(4);
    let animationFrameDurationMs = $state(200);
    let controller: AbortController | null = null;

    const readySelection = $derived(
        $assetGenerationSettings.lifecycle === "connected" ? assetGenerationSettings.getReadySelection() : undefined,
    );
    const stagedWoka = $derived(frontIdleFirst && isWokaTarget(target));
    const busy = $derived(lifecycle === "connecting" || lifecycle === "generating" || lifecycle === "cancelling");
    const displayedLifecycle = $derived(
        lifecycle === "idle" || lifecycle === "ready" ? (readySelection === undefined ? "idle" : "ready") : lifecycle,
    );

    onMount(() => {
        assetGenerationSettings
            .initialize()
            .then(() => assetGenerationSettings.restoreExistingHostedConnection())
            .catch(() => undefined);
    });

    async function addReferences(event: Event) {
        error = "";
        const input = event.currentTarget as HTMLInputElement;
        const files = [...(input.files ?? [])];
        try {
            await Promise.all(files.map((file) => references.add(file, new AbortController().signal)));
            referencePreviews = references.list().map(({ id, objectUrl }) => ({ id, objectUrl }));
        } catch (reason) {
            error = reason instanceof Error ? reason.message : "The reference image could not be added.";
        } finally {
            input.value = "";
        }
    }

    function removeReference(id: string) {
        references.remove(id);
        referencePreviews = references.list().map(({ id: referenceId, objectUrl }) => ({ id: referenceId, objectUrl }));
    }

    function requestGeneration() {
        error = "";
        if (prompt.trim() === "" && onUseImage !== undefined) {
            onUseImage();
            return;
        }
        const selection = assetGenerationSettings.getReadySelection();
        if (selection === undefined) {
            error = "Configure an image provider and model in AI settings first.";
            aiGenerationSettingsVisibilityStore.open();
            return;
        }
        if (prompt.trim() === "") {
            error = "Describe the asset before generating.";
            return;
        }
        if (
            (!stagedWoka || wokaStage === "idle-frame") &&
            requiredReferenceCount !== undefined &&
            references.list().length !== requiredReferenceCount
        ) {
            error = `Add exactly ${requiredReferenceCount} reference image${requiredReferenceCount === 1 ? "" : "s"} before generating.`;
            return;
        }
        if (stagedWoka && wokaStage === "sprite-sheet" && acceptedIdleFrame === null) {
            error = "Accept a front-facing idle frame before generating the sprite sheet.";
            return;
        }
        generate(selection).catch((reason: unknown) => {
            lifecycle = "failed";
            error = reason instanceof Error ? reason.message : "Generation failed.";
        });
    }

    async function generate(selection: { providerId: AssetGenerationProviderId; modelId: string }) {
        lifecycle = "generating";
        error = "";
        const generationController = new AbortController();
        controller = generationController;
        let generationAuthorized = false;
        try {
            const generation = createCurrentGeneration(selection.modelId);
            const approvalId = authorizeGeneration === undefined ? crypto.randomUUID() : await authorizeGeneration();
            generationAuthorized = true;
            const result = await assetGenerationSession.worker.generate(
                {
                    approvalId,
                    approvedAt: new Date().toISOString(),
                    metadata: {
                        providerId: selection.providerId,
                        modelId: selection.modelId,
                        target: generation.request.target,
                        outputCount: 1,
                        maximumCost:
                            maximumCostUsd === undefined
                                ? { kind: "unknown", reason: "Provider pricing is not available before this call." }
                                : { kind: "known", currency: "USD", maximumAmount: maximumCostUsd },
                    },
                    request: generation.request,
                    titlePrompt: prompt,
                },
                {
                    signal: generationController.signal,
                    onLifecycleEvent: (event) => {
                        lifecycle = event.state;
                    },
                },
            );
            const generated = result.assets[0];
            if (generated === undefined) throw new Error("The provider returned no image.");
            const normalized = await normalizeGeneratedRaster(generated.blob, generation.outputSize, {
                removeOpaqueEdgeBackground: true,
            });
            if (candidateUrl !== "") URL.revokeObjectURL(candidateUrl);
            candidate = normalized;
            candidateUrl = URL.createObjectURL(normalized);
            candidateProvenance = {
                title: result.title,
                providerId: selection.providerId,
                modelId: selection.modelId,
                prompt,
                animation: generation.animation,
            };
            try {
                await onGenerated?.({ blob: normalized, ...candidateProvenance });
            } catch (reason) {
                lifecycle = "failed";
                error = reason instanceof Error ? reason.message : "The generated asset could not be saved locally.";
                return;
            }
            lifecycle = "succeeded";
            references.clear();
            referencePreviews = [];
        } catch (reason) {
            const cancelled = generationController.signal.aborted;
            lifecycle = cancelled ? "cancelled" : "failed";
            error = reason instanceof Error ? reason.message : "Generation failed.";
            if (generationAuthorized && onGenerationFailure !== undefined) {
                try {
                    await onGenerationFailure(cancelled ? "cancelled" : "provider-error");
                } catch {
                    error = `${error} The proposal status could not be updated.`;
                }
            }
        } finally {
            controller = null;
        }
    }

    function cancelGeneration() {
        if (controller === null) return;
        lifecycle = "cancelling";
        controller.abort();
    }

    async function acceptCandidate() {
        if (candidate === null || candidateProvenance === null) return;
        if (stagedWoka && wokaStage === "idle-frame") {
            acceptIdleFrameCandidate();
            return;
        }
        lifecycle = "connecting";
        error = "";
        try {
            await onAccept({ blob: candidate, ...candidateProvenance });
            clearCandidate();
            lifecycle = "ready";
        } catch (reason) {
            lifecycle = "failed";
            error = reason instanceof Error ? reason.message : "The asset could not be saved.";
        }
    }

    async function discardCandidate() {
        error = "";
        try {
            if (!stagedWoka || wokaStage === "sprite-sheet") await onDiscardCandidate?.();
            clearCandidate();
        } catch (reason) {
            error = reason instanceof Error ? reason.message : "The generated candidate could not be discarded.";
        }
    }

    onDestroy(() => {
        controller?.abort();
        references.dispose();
        if (candidateUrl !== "") URL.revokeObjectURL(candidateUrl);
        if (acceptedIdleFrameUrl !== "") URL.revokeObjectURL(acceptedIdleFrameUrl);
    });

    function acceptIdleFrameCandidate() {
        if (candidate === null) return;
        if (acceptedIdleFrameUrl !== "") URL.revokeObjectURL(acceptedIdleFrameUrl);
        acceptedIdleFrame = candidate;
        acceptedIdleFrameUrl = candidateUrl;
        candidate = null;
        candidateUrl = "";
        candidateProvenance = null;
        wokaStage = "sprite-sheet";
        lifecycle = "ready";
    }

    function restartIdleFrame() {
        clearCandidate();
        if (acceptedIdleFrameUrl !== "") URL.revokeObjectURL(acceptedIdleFrameUrl);
        acceptedIdleFrame = null;
        acceptedIdleFrameUrl = "";
        wokaStage = "idle-frame";
        lifecycle = "ready";
        error = "";
    }

    function clearCandidate() {
        candidate = null;
        candidateProvenance = null;
        if (candidateUrl !== "") URL.revokeObjectURL(candidateUrl);
        candidateUrl = "";
    }

    function createCurrentGeneration(modelId: string): {
        request: AssetGenerationRequest;
        outputSize?: RasterOutputSize;
        animation?: VisualAssetAnimationValue;
    } {
        if (!stagedWoka || !isWokaTarget(target)) {
            const animation = createAnimationMetadata(target, outputSize);
            const generationOutputSize =
                animation === undefined
                    ? outputSize
                    : {
                          width: animation.frameWidth * animation.frameCount,
                          height: animation.frameHeight,
                          pixelated: outputSize?.pixelated,
                      };
            return {
                request: {
                    modelId,
                    target,
                    prompt: buildGuidedPrompt(prompt, target, generationOutputSize, animation, generationRules),
                    outputCount: 1,
                    references: [...presetReferences, ...references.forGeneration()],
                    outputFormat: "webp",
                    background: "transparent",
                    animation,
                },
                outputSize: generationOutputSize,
                animation,
            };
        }
        if (wokaStage === "idle-frame") {
            const stage = createWokaIdleFrameStage({
                modelId,
                target,
                description: prompt,
                references: references.forGeneration(),
            });
            return stage;
        }
        if (acceptedIdleFrame === null) throw new Error("Accept a front-facing idle frame first.");
        const acceptedSeed: AssetGenerationReference = {
            id: "accepted-front-idle-frame",
            blob: acceptedIdleFrame,
            mimeType: "image/png",
        };
        return createWokaSpriteSheetStage({ modelId, target, description: prompt, acceptedSeed });
    }

    function createAnimationMetadata(
        generationTarget: AssetGenerationTarget,
        size?: RasterOutputSize,
    ): VisualAssetAnimationValue | undefined {
        if (!allowAnimation || !animateAsset || isWokaTarget(generationTarget)) return undefined;
        const frameWidth = generationTarget === "tileset" ? 32 : (size?.width ?? 512);
        const frameHeight = generationTarget === "tileset" ? 32 : (size?.height ?? 512);
        const frameCount = Math.max(2, Math.min(8, Math.round(animationFrameCount)));
        const durationMs = Math.max(50, Math.min(2000, Math.round(animationFrameDurationMs)));
        return VisualAssetAnimation.parse({
            frameWidth,
            frameHeight,
            frameCount,
            frameDurationMs: durationMs,
        });
    }

    function buildGuidedPrompt(
        description: string,
        generationTarget: AssetGenerationTarget,
        size?: RasterOutputSize,
        animation?: VisualAssetAnimationValue,
        extraRules = "",
    ) {
        const sizeRule = size === undefined ? "" : ` Output exactly one ${size.width}×${size.height} pixel PNG.`;
        const targetRule =
            generationTarget === "tileset"
                ? " Create exactly one seamless top-down 2D floor or terrain texture that fills the entire image. Do not include furniture, props, gutters, text, borders, perspective scenery, or multiple tiles."
                : generationTarget === "terrain-surface"
                  ? " Create one square, top-down terrain-surface source on a transparent background. Keep the complete specimen inside the canvas with no text, frame, shadow, floor, scenery, or detached elements."
                  : generationTarget.startsWith("woka-") || generationTarget === "complete-woka"
                    ? ` Use the ${BRANDING.name} Woka sprite-sheet layout: four rows ordered down, left, right, up; three aligned frames per row; transparent background; no text, border, shadow, or scenery.`
                    : " Isolate the object on one flat electric-magenta #FF00FF background, using a readable top-down 2D game perspective and no text or border. The #FF00FF matte must not appear anywhere on the object, including its outline, highlights, shadows, texture, reflections, or semi-transparent edges.";
        const animationRule =
            animation === undefined
                ? ""
                : ` Create one horizontal sprite strip containing exactly ${animation.frameCount} equally sized animation frames, ordered left to right. Keep the subject, scale, camera, palette, lighting, and transparent background consistent. Each frame must be a subtle consecutive motion phase; do not add gutters, labels, borders, or a contact sheet.`;
        const additionalRule = extraRules.trim() === "" ? "" : ` ${extraRules.trim()}`;
        return `${description.trim()}.${sizeRule}${targetRule}${additionalRule}${animationRule}`;
    }

    function isWokaTarget(value: AssetGenerationTarget): value is WokaGenerationTarget {
        return value === "complete-woka" || value.startsWith("woka-");
    }
</script>

<section
    class={compact ? "text-white" : "rounded-xl border border-white/15 bg-black/25 p-3 text-white"}
    aria-label={title}
>
    <div class={compact ? "mb-2" : "mb-3 flex items-center justify-between gap-2"}>
        <div>
            <h3 class={compact ? "text-base font-semibold" : "font-semibold"}>{title}</h3>
            {#if !compact}<p class="text-xs text-white/65">{promptGuidance}</p>{/if}
        </div>
        {#if !compact}
            <span class="rounded-full bg-white/10 px-2 py-1 text-[11px]" aria-live="polite">{displayedLifecycle}</span>
        {/if}
    </div>

    {#if error}<p class="mb-3 text-sm text-red-300" role="alert">{error}</p>{/if}

    {#if stagedWoka}
        <ol class="mb-3 grid grid-cols-2 gap-2 text-xs" aria-label="Avatar generation steps">
            <li
                class={`rounded border p-2 ${wokaStage === "idle-frame" ? "border-secondary bg-secondary/15 text-white" : "border-emerald-300/40 bg-emerald-950/20 text-emerald-100"}`}
            >
                <strong>1. Front idle</strong><br />Approve one detailed 240px design.
            </li>
            <li
                class={`rounded border p-2 ${wokaStage === "sprite-sheet" ? "border-secondary bg-secondary/15 text-white" : "border-white/10 text-white/45"}`}
            >
                <strong>2. Directions</strong><br />Expand the approved frame.
            </li>
        </ol>
    {/if}

    {#if readySelection === undefined && !compact}
        <div class="rounded-lg border border-white/15 bg-black/20 p-3">
            <p class="text-sm font-semibold">Set up AI generation once</p>
            <p class="mt-1 text-xs text-white/65">
                Connect a provider and choose a model in AI models settings. Editors reuse that selection.
            </p>
            <div class="mt-3">
                <Button variant="primary" size="sm" onclick={() => aiGenerationSettingsVisibilityStore.open()}
                    >Open AI settings</Button
                >
            </div>
        </div>
    {:else}
        {#if stagedWoka && wokaStage === "sprite-sheet" && acceptedIdleFrameUrl !== ""}
            <div class="mb-3 flex items-center gap-3 rounded-lg border border-emerald-300/30 bg-emerald-950/20 p-3">
                <img
                    src={acceptedIdleFrameUrl}
                    alt="Accepted front-facing idle frame"
                    class="h-16 w-16 flex-none rounded border border-white/15 object-contain [image-rendering:pixelated]"
                />
                <div class="min-w-0 flex-1">
                    <p class="text-sm font-semibold text-emerald-100">Front idle frame approved</p>
                    <p class="mt-1 text-xs text-white/65">
                        This exact frame is the required reference for every direction and walking pose.
                    </p>
                </div>
                <Button appearance="border" size="sm" onclick={restartIdleFrame} disabled={busy}>Start over</Button>
            </div>
        {/if}
        <label class="mt-2 block text-xs">
            {#if !compact}Description{/if}
            <textarea
                bind:value={prompt}
                rows="3"
                class={compact
                    ? "w-full resize-y rounded bg-black/40 p-2"
                    : "mt-1 w-full resize-y rounded bg-black/40 p-2"}
                placeholder={promptPlaceholder}
                readonly={promptReadOnly}
                aria-label={compact ? "Description" : undefined}
            ></textarea>
        </label>
        {#if !stagedWoka && allowAnimation}
            <div class="mt-3 rounded-lg border border-white/10 bg-black/20 p-2 text-xs">
                <label class="flex cursor-pointer items-center justify-between gap-3">
                    <span>
                        <strong class="block">Animate this asset</strong>
                        <span class="text-white/60">Generate one short looping sprite strip.</span>
                    </span>
                    <input type="checkbox" bind:checked={animateAsset} aria-label="Animate this asset" />
                </label>
                {#if animateAsset}
                    <div class="mt-2 grid grid-cols-2 gap-2">
                        <label>
                            Frames
                            <input
                                class="mt-1 w-full rounded bg-black/40 p-2"
                                type="number"
                                min="2"
                                max="8"
                                bind:value={animationFrameCount}
                            />
                        </label>
                        <label>
                            Frame duration (ms)
                            <input
                                class="mt-1 w-full rounded bg-black/40 p-2"
                                type="number"
                                min="50"
                                max="2000"
                                step="25"
                                bind:value={animationFrameDurationMs}
                            />
                        </label>
                    </div>
                {/if}
            </div>
        {:else}
            <p class="mt-2 text-xs text-white/60">Woka sheets include directional idle and walking animation.</p>
        {/if}
        {#if (!stagedWoka || wokaStage === "idle-frame") && !compact}
            <label class="mt-2 block text-xs">
                Reference images (kept only for this generation)
                <input
                    class="mt-1 block w-full text-xs"
                    type="file"
                    accept="image/png,image/jpeg,image/webp"
                    multiple
                    onchange={addReferences}
                />
            </label>
            {#if referencePreviews.length > 0}
                <div class="mt-2 flex flex-wrap gap-2">
                    {#each referencePreviews as reference (reference.id)}
                        <button
                            class="relative rounded border border-white/20 p-1"
                            onclick={() => removeReference(reference.id)}
                            aria-label="Remove reference image"
                        >
                            <img src={reference.objectUrl} alt="Reference" class="h-12 w-12 object-cover" />
                            <span class="absolute -right-1 -top-1 rounded-full bg-black px-1">×</span>
                        </button>
                    {/each}
                </div>
            {/if}
            {#if requiredReferenceCount !== undefined}
                <p class="mt-1 text-xs text-white/65">
                    {referencePreviews.length} of {requiredReferenceCount} required references selected
                </p>
            {/if}
        {/if}
        <div class={compact ? "mt-3 flex items-center justify-between gap-2" : "mt-3 flex flex-wrap gap-2"}>
            {#if compact && prompt.trim() !== ""}
                <Button
                    appearance="border"
                    size="sm"
                    onclick={() => aiGenerationSettingsVisibilityStore.open()}
                    disabled={busy}>AI settings</Button
                >
            {/if}
            {#if lifecycle === "generating" || lifecycle === "cancelling"}
                <Button variant="danger" size="sm" onclick={cancelGeneration}>Cancel</Button>
            {:else}
                <Button
                    variant="primary"
                    size="sm"
                    onclick={requestGeneration}
                    disabled={busy ||
                        (prompt.trim() === "" && onUseImage === undefined) ||
                        ((!stagedWoka || wokaStage === "idle-frame") &&
                            requiredReferenceCount !== undefined &&
                            referencePreviews.length !== requiredReferenceCount)}
                    >{prompt.trim() === "" && onUseImage !== undefined ? "Use image" : "Generate"}</Button
                >
            {/if}
            {#if !compact}
                <Button
                    appearance="border"
                    size="sm"
                    onclick={() => aiGenerationSettingsVisibilityStore.open()}
                    disabled={busy}>AI settings</Button
                >
            {/if}
        </div>
    {/if}

    {#if lifecycle === "generating" || lifecycle === "cancelling"}
        <div class="mt-3 rounded-lg border border-secondary/40 bg-secondary/10 p-3" role="status" aria-live="polite">
            <div class="mx-auto flex h-[240px] w-[240px] max-w-full items-center justify-center rounded bg-black/20">
                <div class="h-40 w-40 animate-pulse rounded-lg border border-secondary/40 bg-secondary/20"></div>
            </div>
            <p class="mt-2 text-center text-xs text-white/70">
                {lifecycle === "cancelling" ? "Cancelling image generation…" : "Generating image…"}
            </p>
        </div>
    {:else if candidate && candidateUrl}
        <div class="mt-3 rounded-lg border border-emerald-300/30 bg-emerald-950/20 p-3">
            <AnimatedAssetPreview
                imageSource={candidateUrl}
                imageAlt="Generated asset preview"
                animation={candidateProvenance?.animation}
                classNames={`mx-auto h-[240px] w-[240px] max-w-full object-contain ${outputSize?.pixelated === true ? "[image-rendering:pixelated]" : ""}`}
            />
            {#if stagedWoka && wokaStage === "idle-frame"}
                <p class="mt-2 text-center text-xs text-white/70">
                    Review this detailed design at 240px. After approval, AI converts it into the smaller directional
                    game frames. Nothing is added to your avatar catalog until the final sheet passes validation.
                </p>
            {/if}
            <div class="mt-2 flex justify-center gap-2">
                <Button variant="success" size="sm" onclick={acceptCandidate}
                    >{stagedWoka && wokaStage === "idle-frame" ? "Approve front idle" : acceptLabel}</Button
                >
                <Button appearance="border" size="sm" onclick={discardCandidate}>Discard</Button>
            </div>
        </div>
    {/if}
</section>
