<script lang="ts">
    import { onDestroy, onMount } from "svelte";
    import type {
        AssetGenerationLifecycleState,
        AssetGenerationProviderId,
        AssetGenerationRequest,
        AssetGenerationReference,
        AssetGenerationTarget,
    } from "../../Services/AssetGeneration/AssetGenerationTypes";
    import { EphemeralReferenceCollection } from "../../Services/AssetGeneration/ReferenceImageNormalizer";
    import { assetGenerationSession } from "../../Services/AssetGeneration/AssetGenerationSession";
    import { assetGenerationSettings } from "../../Services/AssetGeneration/AssetGenerationSettings";
    import {
        createWokaIdleFrameStage,
        createWokaSpriteSheetStage,
        type WokaGenerationTarget,
    } from "../../Services/AssetGeneration/StagedWokaGeneration";
    import {
        normalizeGeneratedRaster,
        type RasterOutputSize,
    } from "../../Services/AssetGeneration/RasterOutputNormalizer";
    import { aiGenerationSettingsVisibilityStore } from "../../Stores/AiGenerationSettingsVisibilityStore";
    import Button from "../UI/Button.svelte";

    interface AcceptedGeneratedAsset {
        blob: Blob;
        providerId: AssetGenerationProviderId;
        modelId: string;
        prompt: string;
    }

    interface Props {
        target: AssetGenerationTarget;
        title?: string;
        promptPlaceholder?: string;
        promptGuidance?: string;
        outputSize?: RasterOutputSize;
        frontIdleFirst?: boolean;
        initialPrompt?: string;
        promptReadOnly?: boolean;
        requiredReferenceCount?: number;
        maximumCostUsd?: number;
        authorizeGeneration?: () => Promise<string>;
        onGenerationFailure?: (reason: "provider-error" | "cancelled") => void | Promise<void>;
        onDiscardCandidate?: () => void | Promise<void>;
        onAccept: (asset: AcceptedGeneratedAsset) => void | Promise<void>;
    }

    let {
        target,
        title = "Create with AI",
        promptPlaceholder = "Describe what you want to create…",
        promptGuidance = "The image is generated by the provider you connect. Teapot applies the world style and asset constraints.",
        outputSize,
        frontIdleFirst = false,
        initialPrompt = "",
        promptReadOnly = false,
        requiredReferenceCount,
        maximumCostUsd,
        authorizeGeneration,
        onGenerationFailure,
        onDiscardCandidate,
        onAccept,
    }: Props = $props();

    const references = new EphemeralReferenceCollection();
    // svelte-ignore state_referenced_locally -- prompts are intentionally seeded once when an editor mounts
    let prompt = $state(initialPrompt);
    let lifecycle = $state<AssetGenerationLifecycleState>("idle");
    let error = $state("");
    let referencePreviews: readonly { id: string; objectUrl: string }[] = $state([]);
    let reviewOpen = $state(false);
    let candidate: Blob | null = $state(null);
    let candidateUrl = $state("");
    let candidateProvenance: Omit<AcceptedGeneratedAsset, "blob"> | null = $state(null);
    let wokaStage: "idle-frame" | "sprite-sheet" = $state("idle-frame");
    let acceptedIdleFrame: Blob | null = $state(null);
    let acceptedIdleFrameUrl = $state("");
    let reviewSelection: { providerId: AssetGenerationProviderId; modelId: string } | null = $state(null);
    let controller: AbortController | null = null;

    const readySelection = $derived(
        $assetGenerationSettings.lifecycle === "connected" ? assetGenerationSettings.getReadySelection() : undefined,
    );
    const stagedWoka = $derived(frontIdleFirst && isWokaTarget(target));
    const busy = $derived(lifecycle === "connecting" || lifecycle === "generating" || lifecycle === "cancelling");
    const displayedLifecycle = $derived(
        lifecycle === "idle" || lifecycle === "ready" ? (readySelection === undefined ? "idle" : "ready") : lifecycle,
    );

    onMount(() => {
        assetGenerationSettings
            .initialize()
            .then(() => assetGenerationSettings.restoreExistingHostedConnection())
            .catch(() => undefined);
    });

    async function addReferences(event: Event) {
        error = "";
        const input = event.currentTarget as HTMLInputElement;
        const files = [...(input.files ?? [])];
        try {
            await Promise.all(files.map((file) => references.add(file, new AbortController().signal)));
            referencePreviews = references.list().map(({ id, objectUrl }) => ({ id, objectUrl }));
        } catch (reason) {
            error = reason instanceof Error ? reason.message : "The reference image could not be added.";
        } finally {
            input.value = "";
        }
    }

    function removeReference(id: string) {
        references.remove(id);
        referencePreviews = references.list().map(({ id: referenceId, objectUrl }) => ({ id: referenceId, objectUrl }));
    }

    function requestApproval() {
        error = "";
        const selection = assetGenerationSettings.getReadySelection();
        if (selection === undefined) {
            error = "Configure an image provider and model in AI settings first.";
            aiGenerationSettingsVisibilityStore.open();
            return;
        }
        if (prompt.trim() === "") {
            error = "Describe the asset before generating.";
            return;
        }
        if (
            (!stagedWoka || wokaStage === "idle-frame") &&
            requiredReferenceCount !== undefined &&
            references.list().length !== requiredReferenceCount
        ) {
            error = `Add exactly ${requiredReferenceCount} reference image${requiredReferenceCount === 1 ? "" : "s"} before generating.`;
            return;
        }
        if (stagedWoka && wokaStage === "sprite-sheet" && acceptedIdleFrame === null) {
            error = "Accept a front-facing idle frame before generating the sprite sheet.";
            return;
        }
        reviewSelection = selection;
        reviewOpen = true;
    }

    async function approveAndGenerate() {
        reviewOpen = false;
        lifecycle = "generating";
        error = "";
        const generationController = new AbortController();
        controller = generationController;
        let generationAuthorized = false;
        try {
            const selection = reviewSelection;
            if (selection === null) throw new Error("Choose an AI provider and model in settings before generating.");
            const generation = createCurrentGeneration(selection.modelId);
            const approvalId = authorizeGeneration === undefined ? crypto.randomUUID() : await authorizeGeneration();
            generationAuthorized = true;
            const result = await assetGenerationSession.worker.generate(
                {
                    approvalId,
                    approvedAt: new Date().toISOString(),
                    metadata: {
                        providerId: selection.providerId,
                        modelId: selection.modelId,
                        target: generation.request.target,
                        outputCount: 1,
                        maximumCost:
                            maximumCostUsd === undefined
                                ? { kind: "unknown", reason: "Provider pricing is not available before this call." }
                                : { kind: "known", currency: "USD", maximumAmount: maximumCostUsd },
                    },
                    request: generation.request,
                },
                {
                    signal: generationController.signal,
                    onLifecycleEvent: (event) => {
                        lifecycle = event.state;
                    },
                },
            );
            const generated = result.assets[0];
            if (generated === undefined) throw new Error("The provider returned no image.");
            const normalized = await normalizeGeneratedRaster(generated.blob, generation.outputSize, {
                removeOpaqueEdgeBackground: true,
            });
            if (candidateUrl !== "") URL.revokeObjectURL(candidateUrl);
            candidate = normalized;
            candidateUrl = URL.createObjectURL(normalized);
            candidateProvenance = {
                providerId: selection.providerId,
                modelId: selection.modelId,
                prompt,
            };
            lifecycle = "succeeded";
            references.clear();
            referencePreviews = [];
        } catch (reason) {
            const cancelled = generationController.signal.aborted;
            lifecycle = cancelled ? "cancelled" : "failed";
            error = reason instanceof Error ? reason.message : "Generation failed.";
            if (generationAuthorized && onGenerationFailure !== undefined) {
                try {
                    await onGenerationFailure(cancelled ? "cancelled" : "provider-error");
                } catch {
                    error = `${error} The proposal status could not be updated.`;
                }
            }
        } finally {
            controller = null;
        }
    }

    function cancelGeneration() {
        if (controller === null) return;
        lifecycle = "cancelling";
        controller.abort();
    }

    async function acceptCandidate() {
        if (candidate === null || candidateProvenance === null) return;
        if (stagedWoka && wokaStage === "idle-frame") {
            acceptIdleFrameCandidate();
            return;
        }
        lifecycle = "connecting";
        error = "";
        try {
            await onAccept({ blob: candidate, ...candidateProvenance });
            clearCandidate();
            lifecycle = "ready";
        } catch (reason) {
            lifecycle = "failed";
            error = reason instanceof Error ? reason.message : "The asset could not be saved.";
        }
    }

    async function discardCandidate() {
        error = "";
        try {
            if (!stagedWoka || wokaStage === "sprite-sheet") await onDiscardCandidate?.();
            clearCandidate();
        } catch (reason) {
            error = reason instanceof Error ? reason.message : "The generated candidate could not be discarded.";
        }
    }

    onDestroy(() => {
        controller?.abort();
        references.dispose();
        if (candidateUrl !== "") URL.revokeObjectURL(candidateUrl);
        if (acceptedIdleFrameUrl !== "") URL.revokeObjectURL(acceptedIdleFrameUrl);
    });

    function acceptIdleFrameCandidate() {
        if (candidate === null) return;
        if (acceptedIdleFrameUrl !== "") URL.revokeObjectURL(acceptedIdleFrameUrl);
        acceptedIdleFrame = candidate;
        acceptedIdleFrameUrl = candidateUrl;
        candidate = null;
        candidateUrl = "";
        candidateProvenance = null;
        reviewSelection = null;
        wokaStage = "sprite-sheet";
        lifecycle = "ready";
    }

    function restartIdleFrame() {
        clearCandidate();
        if (acceptedIdleFrameUrl !== "") URL.revokeObjectURL(acceptedIdleFrameUrl);
        acceptedIdleFrame = null;
        acceptedIdleFrameUrl = "";
        reviewSelection = null;
        reviewOpen = false;
        wokaStage = "idle-frame";
        lifecycle = "ready";
        error = "";
    }

    function clearCandidate() {
        candidate = null;
        candidateProvenance = null;
        if (candidateUrl !== "") URL.revokeObjectURL(candidateUrl);
        candidateUrl = "";
        reviewSelection = null;
    }

    function createCurrentGeneration(modelId: string): {
        request: AssetGenerationRequest;
        outputSize?: RasterOutputSize;
    } {
        if (!stagedWoka || !isWokaTarget(target)) {
            return {
                request: {
                    modelId,
                    target,
                    prompt: buildGuidedPrompt(prompt, target, outputSize),
                    outputCount: 1,
                    references: references.forGeneration(),
                    outputFormat: "webp",
                    background: "transparent",
                },
                outputSize,
            };
        }
        if (wokaStage === "idle-frame") {
            const stage = createWokaIdleFrameStage({
                modelId,
                target,
                description: prompt,
                references: references.forGeneration(),
            });
            return stage;
        }
        if (acceptedIdleFrame === null) throw new Error("Accept a front-facing idle frame first.");
        const acceptedSeed: AssetGenerationReference = {
            id: "accepted-front-idle-frame",
            blob: acceptedIdleFrame,
            mimeType: "image/png",
        };
        return createWokaSpriteSheetStage({ modelId, target, description: prompt, acceptedSeed });
    }

    function buildGuidedPrompt(description: string, generationTarget: AssetGenerationTarget, size?: RasterOutputSize) {
        const sizeRule = size === undefined ? "" : ` Output exactly one ${size.width}×${size.height} pixel PNG.`;
        const targetRule =
            generationTarget === "tileset"
                ? " Create exactly one seamless top-down 2D floor or terrain texture that fills the entire image. Do not include furniture, props, gutters, text, borders, perspective scenery, or multiple tiles."
                : generationTarget.startsWith("woka-") || generationTarget === "complete-woka"
                  ? " Use the WorkAdventure Woka sprite-sheet layout: four rows ordered down, left, right, up; three aligned frames per row; transparent background; no text, border, shadow, or scenery."
                  : " Isolate the object on a transparent background, using a readable top-down 2D game perspective and no text or border.";
        return `${description.trim()}.${sizeRule}${targetRule}`;
    }

    function isWokaTarget(value: AssetGenerationTarget): value is WokaGenerationTarget {
        return value === "complete-woka" || value.startsWith("woka-");
    }

    function providerLabel(providerId?: AssetGenerationProviderId): string {
        return providerId === "openrouter"
            ? "OpenRouter"
            : providerId === "codex-cli"
              ? "Codex subscription"
              : providerId === "claude-cli"
                ? "Claude subscription"
                : "AI provider";
    }

    function currentProviderName(): string {
        const selectedProvider = reviewSelection === null ? readySelection?.providerId : reviewSelection.providerId;
        return providerLabel(selectedProvider);
    }
</script>

<section class="rounded-xl border border-white/15 bg-black/25 p-3 text-white" aria-label={title}>
    <div class="mb-3 flex items-center justify-between gap-2">
        <div>
            <h3 class="font-semibold">{title}</h3>
            <p class="text-xs text-white/65">{promptGuidance}</p>
        </div>
        <span class="rounded-full bg-white/10 px-2 py-1 text-[11px]" aria-live="polite">{displayedLifecycle}</span>
    </div>

    {#if error}<p class="mb-3 text-sm text-red-300" role="alert">{error}</p>{/if}

    {#if stagedWoka}
        <ol class="mb-3 grid grid-cols-2 gap-2 text-xs" aria-label="Avatar generation steps">
            <li
                class={`rounded border p-2 ${wokaStage === "idle-frame" ? "border-secondary bg-secondary/15 text-white" : "border-emerald-300/40 bg-emerald-950/20 text-emerald-100"}`}
            >
                <strong>1. Front idle</strong><br />Approve one detailed 240px design.
            </li>
            <li
                class={`rounded border p-2 ${wokaStage === "sprite-sheet" ? "border-secondary bg-secondary/15 text-white" : "border-white/10 text-white/45"}`}
            >
                <strong>2. Directions</strong><br />Expand the approved frame.
            </li>
        </ol>
    {/if}

    {#if readySelection === undefined}
        <div class="rounded-lg border border-white/15 bg-black/20 p-3">
            <p class="text-sm font-semibold">Set up AI generation once</p>
            <p class="mt-1 text-xs text-white/65">
                Connect a provider and choose a model in AI models settings. Editors reuse that selection.
            </p>
            <div class="mt-3">
                <Button variant="primary" size="sm" onclick={() => aiGenerationSettingsVisibilityStore.open()}
                    >Open AI settings</Button
                >
            </div>
        </div>
    {:else}
        {#if stagedWoka && wokaStage === "sprite-sheet" && acceptedIdleFrameUrl !== ""}
            <div class="mb-3 flex items-center gap-3 rounded-lg border border-emerald-300/30 bg-emerald-950/20 p-3">
                <img
                    src={acceptedIdleFrameUrl}
                    alt="Accepted front-facing idle frame"
                    class="h-16 w-16 flex-none rounded border border-white/15 object-contain [image-rendering:pixelated]"
                />
                <div class="min-w-0 flex-1">
                    <p class="text-sm font-semibold text-emerald-100">Front idle frame approved</p>
                    <p class="mt-1 text-xs text-white/65">
                        This exact frame is the required reference for every direction and walking pose.
                    </p>
                </div>
                <Button appearance="border" size="sm" onclick={restartIdleFrame} disabled={busy}>Start over</Button>
            </div>
        {/if}
        <label class="mt-2 block text-xs">
            Description
            <textarea
                bind:value={prompt}
                rows="3"
                class="mt-1 w-full resize-y rounded bg-black/40 p-2"
                placeholder={promptPlaceholder}
                readonly={promptReadOnly}
            ></textarea>
        </label>
        {#if !stagedWoka || wokaStage === "idle-frame"}
            <label class="mt-2 block text-xs">
                Reference images (kept only for this generation)
                <input
                    class="mt-1 block w-full text-xs"
                    type="file"
                    accept="image/png,image/jpeg,image/webp"
                    multiple
                    onchange={addReferences}
                />
            </label>
            {#if referencePreviews.length > 0}
                <div class="mt-2 flex flex-wrap gap-2">
                    {#each referencePreviews as reference (reference.id)}
                        <button
                            class="relative rounded border border-white/20 p-1"
                            onclick={() => removeReference(reference.id)}
                            aria-label="Remove reference image"
                        >
                            <img src={reference.objectUrl} alt="Reference" class="h-12 w-12 object-cover" />
                            <span class="absolute -right-1 -top-1 rounded-full bg-black px-1">×</span>
                        </button>
                    {/each}
                </div>
            {/if}
            {#if requiredReferenceCount !== undefined}
                <p class="mt-1 text-xs text-white/65">
                    {referencePreviews.length} of {requiredReferenceCount} required references selected
                </p>
            {/if}
        {/if}
        <div class="mt-3 flex flex-wrap gap-2">
            {#if lifecycle === "generating" || lifecycle === "cancelling"}
                <Button variant="danger" size="sm" onclick={cancelGeneration}>Cancel</Button>
            {:else}
                <Button
                    variant="primary"
                    size="sm"
                    onclick={requestApproval}
                    disabled={busy ||
                        prompt.trim() === "" ||
                        ((!stagedWoka || wokaStage === "idle-frame") &&
                            requiredReferenceCount !== undefined &&
                            referencePreviews.length !== requiredReferenceCount)}
                    >{stagedWoka && wokaStage === "sprite-sheet"
                        ? "Review direction generation"
                        : stagedWoka
                          ? "Review front-idle generation"
                          : "Review generation"}</Button
                >
            {/if}
            <Button
                appearance="border"
                size="sm"
                onclick={() => aiGenerationSettingsVisibilityStore.open()}
                disabled={busy}>AI settings</Button
            >
        </div>
    {/if}

    {#if reviewOpen}
        <div
            class="mt-3 rounded-lg border border-amber-300/40 bg-amber-950/30 p-3"
            role="alertdialog"
            aria-label="Approve paid generation"
        >
            <p class="text-sm">
                <strong>{currentProviderName()}</strong> will receive your prompt{referencePreviews.length > 0 ||
                (stagedWoka && wokaStage === "sprite-sheet")
                    ? " and reference images"
                    : ""} and create one
                {stagedWoka
                    ? wokaStage === "idle-frame"
                        ? "front-facing idle draft"
                        : "directional walking sheet"
                    : "image"}
                with <strong>{reviewSelection?.modelId ?? "the configured model"}</strong>.
            </p>
            <p class="mt-1 text-xs text-amber-100">
                {maximumCostUsd === undefined
                    ? "Maximum cost is unknown because the provider did not return a preflight price."
                    : `The proposal states a maximum cost of $${maximumCostUsd.toFixed(2)}.`}
                This approval authorizes exactly one call and is never retried automatically.
            </p>
            <div class="mt-2 flex gap-2">
                <Button variant="warning" size="sm" onclick={approveAndGenerate}>Approve and generate</Button>
                <Button appearance="border" size="sm" onclick={() => (reviewOpen = false)}>Back</Button>
            </div>
        </div>
    {/if}

    {#if candidate && candidateUrl}
        <div class="mt-3 rounded-lg border border-emerald-300/30 bg-emerald-950/20 p-3">
            <img
                src={candidateUrl}
                alt="Generated asset preview"
                class="mx-auto h-[240px] w-[240px] max-w-full object-contain [image-rendering:pixelated]"
            />
            {#if stagedWoka && wokaStage === "idle-frame"}
                <p class="mt-2 text-center text-xs text-white/70">
                    Review this detailed design at 240px. After approval, AI converts it into the smaller directional
                    game frames. Nothing is added to your avatar catalog until the final sheet passes validation.
                </p>
            {/if}
            <div class="mt-2 flex justify-center gap-2">
                <Button variant="success" size="sm" onclick={acceptCandidate}
                    >{stagedWoka && wokaStage === "idle-frame" ? "Approve front idle" : "Use this asset"}</Button
                >
                <Button appearance="border" size="sm" onclick={discardCandidate}>Discard</Button>
            </div>
        </div>
    {/if}
</section>
