export {
    BUILT_IN_ATLAS_ASSET_KINDS,
    BUILT_IN_ATLAS_ASSETS,
    BUILT_IN_TERRAIN_ASSETS,
    BUILT_IN_TERRAIN_CATALOG_VERSION,
    BUILT_IN_TERRAIN_TILESET,
    BUILT_IN_TERRAIN_TYPES,
    getBuiltInTerrainAsset,
    getBuiltInTerrainTileIds,
    searchBuiltInAtlasAssets,
    searchBuiltInTerrainAssets,
    type BuiltInAtlasAsset,
    type BuiltInAtlasAssetKind,
    type BuiltInAtlasAssetSearch,
    type BuiltInAtlasPlacement,
    type BuiltInTerrainAsset,
    type BuiltInTerrainGroup,
    type BuiltInTerrainSearch,
    type BuiltInTerrainType,
} from "../../common/Teapot/BuiltInTerrainCatalog";
