export {
    BUILT_IN_ATLAS_ASSET_KINDS,
    BUILT_IN_ATLAS_ASSETS,
    ALL_BUILT_IN_TERRAIN_ASSETS,
    BUILT_IN_SUMMER_TERRAIN_ASSETS,
    BUILT_IN_SUMMER_TERRAIN_TILESET,
    BUILT_IN_TERRAIN_ASSETS,
    BUILT_IN_TERRAIN_CATALOG_VERSION,
    BUILT_IN_TERRAIN_TILESET,
    BUILT_IN_TERRAIN_TILESETS,
    BUILT_IN_TERRAIN_TYPES,
    getBuiltInTerrainAsset,
    getBuiltInTerrainAssetsForTileset,
    getBuiltInTerrainAutotile,
    getBuiltInTerrainTileset,
    getBuiltInWaterFillTileId,
    getBuiltInTerrainTileIds,
    getBuiltInTerrainTileIdsForTileset,
    searchBuiltInAtlasAssets,
    searchBuiltInTerrainAssets,
    type BuiltInAtlasAsset,
    type BuiltInAtlasAssetKind,
    type BuiltInAtlasAssetSearch,
    type BuiltInAtlasPlacement,
    type BuiltInTerrainAsset,
    type BuiltInTerrainGroup,
    type BuiltInTerrainSearch,
    type BuiltInTerrainTileset,
    type BuiltInTerrainType,
} from "../../common/Teapot/BuiltInTerrainCatalog";

export {
    TERRAIN_SPRITE_TEMPLATE_PROFILES,
    TERRAIN_SURFACE_CATALOG_VERSION,
    TERRAIN_SURFACE_CATEGORIES,
    TERRAIN_SURFACE_SPRITE_ROLES,
    TERRAIN_SURFACES,
    getTerrainSurface,
    getTerrainSurfaceSpriteRequirements,
    searchTerrainSurfaces,
    validateTerrainSurfaceCatalog,
    type TerrainAssetAvailability,
    type TerrainAssetReadiness,
    type TerrainAtlasTileSource,
    type TerrainCompositionMode,
    type TerrainEffect,
    type TerrainEffectType,
    type TerrainSpecialSpriteAsset,
    type TerrainSpriteAsset,
    type TerrainSpriteRoleDefinition,
    type TerrainSpriteTemplateProfile,
    type TerrainSurface,
    type TerrainSurfaceAssets,
    type TerrainSurfaceCategory,
    type TerrainSurfaceSearch,
    type TerrainSurfaceSpriteRole,
    type TerrainTraversal,
    type TerrainTraversalMode,
    type TerrainWaterAppearance,
    type TerrainWaterColor,
    type TerrainWaterKind,
    type TerrainWaterWaveform,
} from "../../common/Teapot/TerrainSurfaceCatalog";

export {
    BUILT_IN_LEGACY_MAP_TILESETS,
    BUILT_IN_MAP_TILESETS,
    getBuiltInMapTileset,
    isLegacyWorkAdventureTileset,
    type BuiltInMapTileset,
    type LegacyWorkAdventureTileset,
} from "../../common/Teapot/BuiltInMapTilesetCatalog";
